name: Main
on:
  - push
  - pull_request_target
jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          # Turning off truffleruby because I'm not sure why it's failing
          # - truffleruby
    runs-on: ${{ matrix.os }}
    env:
      PLUGIN_RUBY_CI: true
    steps:
      - name: Checkout from pull_request_target event
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@master
        with:
          ref: ${{ github.sha }}
      - name: Checkout from push
        if: github.event_name == 'push'
        uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
      - id: yarn-cache
        run: echo "::set-output name=directory::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.directory }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - name: Test
        run: |
          yarn test
          bundle exec rake test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      PLUGIN_RUBY_CI: true
    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "3.0"
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
      - id: yarn-cache
        run: echo "::set-output name=directory::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.directory }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: |
          yarn check-format
          yarn lint

  automerge:
    name: Auto Merge
    needs:
      - ci
      - lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
